const coins = [
  { name: " ", isoCode: " " },
  { name: "Afghani (AFN)", isoCode: "AFN" },
  { name: "Ariary malgaxe (MGA)", isoCode: "MGA" },
  { name: "Baht (THB)", isoCode: "THB" },
  { name: "Balboa (PAB)", isoCode: "PAB" },
  { name: "Birr etíope (ETB)", isoCode: "ETB" },
  { name: "Bolívar (VEF)", isoCode: "VEF" },
  { name: "Boliviano (BOB)", isoCode: "BOB" },
  { name: "Cabo Verde Escudo (CVE)", isoCode: "CVE" },
  { name: "CFA Franc BCEAO (XOF)", isoCode: "XOF" },
  { name: "CFA Franc BEAC (XAF)", isoCode: "XAF" },
  { name: "CFA Franco BCEAO (XOF)", isoCode: "XOF" },
  { name: "CFP Franc (XPF)", isoCode: "XPF" },
  { name: "Colon da Costa Rica (CRC)", isoCode: "CRC" },
  { name: "Cólon de El Salvador (SVC)", isoCode: "SVC" },
  { name: "Cordoba Oro (NIO)", isoCode: "NIO" },
  { name: "Coroa da Islândia (ISK)", isoCode: "ISK" },
  { name: "Coroa dinamarquesa (DKK)", isoCode: "DKK" },
  { name: "Coroa norueguesa (NOK)", isoCode: "NOK" },
  { name: "Coroa Tcheca (CZK)", isoCode: "CZK" },
  { name: "Dalasi (GMD)", isoCode: "GMD" },
  { name: "Denar (MKD)", isoCode: "MKD" },
  { name: "Dinar argelino (DZD)", isoCode: "DZD" },
  { name: "Dinar da Líbia (LYD)", isoCode: "LYD" },
  { name: "Dinar do Bahrein (BHD)", isoCode: "BHD" },
  { name: "Dinar iraquiano (IQD)", isoCode: "IQD" },
  { name: "Dinar jordaniano (JOD)", isoCode: "JOD" },
  { name: "Dinar sérvio (RSD)", isoCode: "RSD" },
  { name: "Dinar tunisino (TND)", isoCode: "TND" },
  { name: "Dirham marroquino (MAD)", isoCode: "MAD" },
  { name: "Dobra (STD)", isoCode: "STD" },
  { name: "Dólar americano (USD)", isoCode: "USD" },
  { name: "Dólar australiano (AUD)", isoCode: "AUD" },
  { name: "Dólar canadense (CAD)", isoCode: "CAD" },
  { name: "Dólar da Guiana (GYD)", isoCode: "GYD" },
  { name: "Dólar da Nova Zelândia (NZD)", isoCode: "NZD" },
  { name: "Dólar das Bahamas (BSD)", isoCode: "BSD" },
  { name: "Dólar das Bermudas (BMD)", isoCode: "BMD" },
  { name: "Dólar das Ilhas Caimã (KYD)", isoCode: "KYD" },
  { name: "Dólar das Ilhas Salomão (SBD)", isoCode: "SBD" },
  { name: "Dólar de Barbados (BBD)", isoCode: "BBD" },
  { name: "Dólar de Belize (BZD)", isoCode: "BZD" },
  { name: "Dólar de Fiji (FJD)", isoCode: "FJD" },
  { name: "Dólar de Hong Kong (HKD)", isoCode: "HKD" },
  { name: "Dólar de Singapura (SGD)", isoCode: "SGD" },
  { name: "Dólar de Trinidad e Tobago (TTD)", isoCode: "TTD" },
  { name: "Dólar do Caribe Oriental (XCD)", isoCode: "XCD" },
  { name: "Dólar do Suriname (SRD)", isoCode: "SRD" },
  { name: "Dólar dos EUA (dia seguinte) (USN)", isoCode: "USN" },
  { name: "Dólar jamaicano (JMD)", isoCode: "JMD" },
  { name: "Dólar liberiano (LRD)", isoCode: "LRD" },
  { name: "Dólar zimbabuano (ZWL)", isoCode: "ZWL" },
  { name: "Dólares da Namíbia (NAD)", isoCode: "NAD" },
  { name: "Dólares de Brunei (BND)", isoCode: "BND" },
  { name: "Dong (VND)", isoCode: "VND" },
  { name: "Dram armênio (AMD)", isoCode: "AMD" },
  { name: "Euro (EUR)", isoCode: "EUR" },
  { name: "Florim de Aruba (AWG)", isoCode: "AWG" },
  { name: "Forint (HUF)", isoCode: "HUF" },
  { name: "Fran congolesac (CDF)", isoCode: "CDF" },
  { name: "Franco Comor (KMF)", isoCode: "KMF" },
  { name: "Franco da Guiné (GNF)", isoCode: "GNF" },
  { name: "Franco do Burundi (BIF)", isoCode: "BIF" },
  { name: "Franco do Djibouti (DJF)", isoCode: "DJF" },
  { name: "Franco suíço (CHF)", isoCode: "CHF" },
  { name: "Ghana Cedi (GHS)", isoCode: "GHS" },
  { name: "Gourde (HTG)", isoCode: "HTG" },
  { name: "Guarani (PYG)", isoCode: "PYG" },
  { name: "Guilder das Antilhas Holandesas (ANG)", isoCode: "ANG" },
  { name: "Hryvnia (UAH)", isoCode: "UAH" },
  { name: "Iene (JPY)", isoCode: "JPY" },
  { name: "Kina (PGK)", isoCode: "PGK" },
  { name: "Kip (LAK)", isoCode: "LAK" },
  { name: "Kuna (HRK)", isoCode: "HRK" },
  { name: "Kwacha (MWK)", isoCode: "MWK" },
  { name: "Kwanza (AOA)", isoCode: "AOA" },
  { name: "Kyat (MMK)", isoCode: "MMK" },
  { name: "Lari (GEL)", isoCode: "GEL" },
  { name: "Leão da Moldávia (MDL)", isoCode: "MDL" },
  { name: "Lek (ALL)", isoCode: "ALL" },
  { name: "Lempira (HNL)", isoCode: "HNL" },
  { name: "Leone (SLL)", isoCode: "SLL" },
  { name: "Leu romeno (RON)", isoCode: "RON" },
  { name: "Lev búlgaro (BGN)", isoCode: "BGN" },
  { name: "Libra das Ilhas Falkland (FKP)", isoCode: "FKP" },
  { name: "Libra De Gibraltar (GIP)", isoCode: "GIP" },
  { name: "Libra egípcia (EGP)", isoCode: "EGP" },
  { name: "Libra esterlina (GBP)", isoCode: "GBP" },
  { name: "Libra libanesa (LBP)", isoCode: "LBP" },
  { name: "Libra síria (SYP)", isoCode: "SYP" },
  { name: "Libra sudanesa (SDG)", isoCode: "SDG" },
  { name: "Libra Sudanesa do Sul (SSP)", isoCode: "SSP" },
  { name: "Lilangeni (SZL)", isoCode: "SZL" },
  { name: "Lira turca (TRY)", isoCode: "TRY" },
  { name: "Loti (LSL)", isoCode: "LSL" },
  { name: "Manat do Azerbaijão (AZN)", isoCode: "AZN" },
  { name: "Marco conversível (BAM)", isoCode: "BAM" },
  { name: "Moçambique Metical (MZN)", isoCode: "MZN" },
  { name: "Moroccan Dirham (MAD)", isoCode: "MAD" },
  { name: "Mvdol (BOV)", isoCode: "BOV" },
  { name: "Naira (NGN)", isoCode: "NGN" },
  { name: "Nakfa (ERN)", isoCode: "ERN" },
  { name: "Ngultrum (BTN)", isoCode: "BTN" },
  { name: "Novo dólar de Taiwan (TWD)", isoCode: "TWD" },
  { name: "Novo Sheqel israelense (ILS)", isoCode: "ILS" },
  { name: "Nuevo Sol (PEN)", isoCode: "PEN" },
  { name: "O Dinar do Kuwait (KWD)", isoCode: "KWD" },
  { name: "Ouguiya (MRO)", isoCode: "MRO" },
  { name: "Pa’anga (TOP)", isoCode: "TOP" },
  { name: "Pataca (MOP)", isoCode: "MOP" },
  { name: "Peso argentino (ARS)", isoCode: "ARS" },
  { name: "Peso chileno (CLP)", isoCode: "CLP" },
  { name: "Peso colombiano (COP)", isoCode: "COP" },
  { name: "Peso conversível (CUC)", isoCode: "CUC" },
  { name: "Peso cubano (CUP)", isoCode: "CUP" },
  { name: "Peso dominicano (DOP)", isoCode: "DOP" },
  { name: "Peso filipino (PHP)", isoCode: "PHP" },
  { name: "Peso mexicano (MXN)", isoCode: "MXN" },
  { name: "Peso Uruguaio (UYU)", isoCode: "UYU" },
  {
    name: "Peso Uruguaio em Unidades Indexadas (URUIURUI) (UYI)",
    isoCode: "UYI",
  },
  { name: "Pula (BWP)", isoCode: "BWP" },
  { name: "Qatari Rial (QAR)", isoCode: "QAR" },
  { name: "Quetzal (GTQ)", isoCode: "GTQ" },
  { name: "Rand (ZAR)", isoCode: "ZAR" },
  { name: "Real brasileiro (BRL)", isoCode: "BRL" },
  { name: "Rial Iemenita (YER)", isoCode: "YER" },
  { name: "Rial iraniano (IRR)", isoCode: "IRR" },
  { name: "Rial Omani (OMR)", isoCode: "OMR" },
  { name: "Rial saudita (SAR)", isoCode: "SAR" },
  { name: "Riel (KHR)", isoCode: "KHR" },
  { name: "Ringgit da Malásia (MYR)", isoCode: "MYR" },
  { name: "Rublo bielorrusso (BYR)", isoCode: "BYR" },
  { name: "rublo russo (RUB)", isoCode: "RUB" },
  { name: "Rufiyaa (MVR)", isoCode: "MVR" },
  { name: "Rupia (IDR)", isoCode: "IDR" },
  { name: "Rupia das Maurícias (MUR)", isoCode: "MUR" },
  { name: "Rúpia das Seychelles (SCR)", isoCode: "SCR" },
  { name: "Rupia do Paquistão (PKR)", isoCode: "PKR" },
  { name: "Rupia do Sri Lanka (LKR)", isoCode: "LKR" },
  { name: "Rupia indiana (INR)", isoCode: "INR" },
  { name: "Rupia nepalesa (NPR)", isoCode: "NPR" },
  { name: "Rwanda Franc (RWF)", isoCode: "RWF" },
  { name: "Saint Helena Pound (SHP)", isoCode: "SHP" },
  { name: "SDR (Special Drawing Right) (XDR)", isoCode: "XDR" },
  { name: "Shilling Somali (SOS)", isoCode: "SOS" },
  { name: "Som (KGS)", isoCode: "KGS" },
  { name: "Soma do Uzbequistão (UZS)", isoCode: "UZS" },
  { name: "Somoni (TJS)", isoCode: "TJS" },
  { name: "Sucre (XSU)", isoCode: "XSU" },
  { name: "Swedish Krona (SEK)", isoCode: "SEK" },
  { name: "Taka (BDT)", isoCode: "BDT" },
  { name: "Tala (WST)", isoCode: "WST" },
  { name: "Tenge (KZT)", isoCode: "KZT" },
  { name: "Tugrik (MNT)", isoCode: "MNT" },
  { name: "Turcomenistão New Manat (TMT)", isoCode: "TMT" },
  { name: "UAE Dirham (AED)", isoCode: "AED" },
  { name: "Unidad de Fomento (CLF)", isoCode: "CLF" },
  { name: "Unidade de Conta do ADB (XUA)", isoCode: "XUA" },
  { name: "Unidade de Investimento Mexicana (UDI) (MXV)", isoCode: "MXV" },
  { name: "Unidade de Valor Real (COU)", isoCode: "COU" },
  { name: "Vatu (VUV)", isoCode: "VUV" },
  { name: "WIR Euro (CHE)", isoCode: "CHE" },
  { name: "WIR Franc (CHW)", isoCode: "CHW" },
  { name: "Won (KRW)", isoCode: "KRW" },
  { name: "Won norte-coreano (KPW)", isoCode: "KPW" },
  { name: "Xelim da Tanzânia (TZS)", isoCode: "TZS" },
  { name: "Xelim de Uganda (UGX)", isoCode: "UGX" },
  { name: "Xelim do Quênia (KES)", isoCode: "KES" },
  { name: "Yuan Renminbi (CNY)", isoCode: "CNY" },
  { name: "Zambian Kwacha (ZMW)", isoCode: "ZMW" },
  { name: "Zloty (PLN)", isoCode: "PLN" },
];

export const coinsName = coins.map((coin) => {
  return coin.name;
});

export default coins;